/*
  Copyright 2011 The University of Texas at Austin

	Advisor: Chandrajit Bajaj <bajaj@cs.utexas.edu>

  This file is part of TexMol.

  TexMol is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License version 2.1 as published by the Free Software Foundation.

  TexMol is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
*/
#ifndef F2DOCK_MASTER_CONTROL
#define F2DOCK_MASTER_CONTROL

#include <F2DockClient/jobParams.h>

#include <F2DockClient/F2DockClient.h>
#include <F2DockClient/quadGenControl.h>
#include <F2DockClient/quadGenDialog.h>

#include <F2DockClient/f2dGenControl.h>
#include <F2DockClient/f2dGenDialog.h>

#include <F2DockClient/rerankControl.h>
#include <F2DockClient/rerankDialog.h>

#include <F2DockClient/dockControl.h>
#include <F2DockClient/dockDialog.h>

#include <F2DockClient/resultControl.h>

#include <F2DockClient/fileManager.h>



class F2dockMasterControl
{
	private:
	vector<JobParams *> jobs;

	F2DockClient *client;	
	ResultControl *resultCont;

	bool showDockingResult(int index);
	bool showRerankingResult(int index);
	bool showF2dGenResult(int index);
	bool showQuadGenResult(int index);

	public:
	F2dockMasterControl();
	~F2dockMasterControl();
	
	void init();

	
	// Actions corresponding to events generated by the UI
	bool handleDockingRequest();
	bool handleRerankingRequest();
	bool handleF2dGenRequest();
	bool handleQuadGenRequest();

	bool createJob(string inputFileName, string outputFileName);
	bool saveJob(int index);
	bool loadJob(string fileName);
	bool closeJob(int index);

	bool showResults(int index);
	bool showDetails(int index);
	bool isRunning(int index);

	bool updateJobStatus(string id, int status);
	

	// get methods to read data to show on the UI
	int getNumberOfJobs(void) {return jobs.size();}

	string getJobId(int index);
	string getJobType(int index);
	string getJobStatus(int index);
	int getJobStatusInt(int index);
	string getJobTitle(int index);

	string getReceptor(int index);
	string getLigand(int index);
	double *getMat(int i, int j);

	ResultControl * getResultControl(int index);
};

#endif
