# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += CoarseGrain

#unix:LIBS += $(CGALLIB)/libCGAL.a
#unix:LIBS += $(CGALLIB)/libCGALQt.a
#unix:LIBS += $(CGALLIB)/libcore++.a
#unix:LIBS += $(CGALLIB)/libCGAL.so
#unix:LIBS += -lgsl -lgslcblas
#unix:LIBS += /usr/lib64/liblapack.a
unix:LIBS += /usr/lib64/atlas/liblapack.a
unix:LIBS += /usr/lib64/atlas/libf77blas.a
unix:LIBS += /usr/lib64/atlas/libcblas.a
unix:LIBS += /usr/lib64/atlas/libatlas.a
unix:LIBS += /usr/lib/gcc/x86_64-redhat-linux/3.4.6/libg2c.a
unix:LIBS += /usr/lib/gcc/x86_64-redhat-linux/4.1.2/libgfortran.a
  
#linux-g++ {
#        INCLUDEPATH += $(CGALINCLUDE)
#        INCLUDEPATH += $(CGALCONFIG)
#}
#linux-g++-64 {
#        INCLUDEPATH += $(CGALINCLUDE)
#        INCLUDEPATH += $(CGALCONFIG)
#}

INCLUDEPATH += ../ \ 
	       /workspace/jgsun/usr/local/include \
	       /usr/include \ 

HEADERS	+= coarseGrain.h \ 

SOURCES	+= coarseGrain.cpp \ 
	   coarseGrainCharge.cpp \ 
	   coarseGrainGeometry.cpp \ 
	   lapackSolver.cpp \ 

