CMAKE_MINIMUM_REQUIRED (VERSION 2.6.2)
PROJECT (TexMol)

ADD_DEFINITIONS(-frounding-math)

SET(CGAL_DIR
  ${PROJECT_BINARY_DIR}/lib/CGAL)

# Global build variables.  Use the standard CPPFLAGS and LDFLAGS env vars.
SET (CMAKE_CXX_FLAGS "-Wno-deprecated -Wno-non-template-friend")
if(CMAKE_HOST_UNIX)
  SET (CMAKE_CXX_FLAGS $ENV{CPPFLAGS})
  SET (CMAKE_LD_FLAGS $ENV{LDFLAGS})
endif(CMAKE_HOST_UNIX)

option(USING_MAKE_ENV_VARS_FOR_INSTALL "If this is enabled, use the LDFLAGS environment variable as a directory to look up libs for a bundle" ON)
mark_as_advanced(USING_MAKE_ENV_VARS_FOR_INSTALL)
if(USING_MAKE_ENV_VARS_FOR_INSTALL)
  set(ENV_LIB_DIR "$ENV{ENV}/lib")
endif(USING_MAKE_ENV_VARS_FOR_INSTALL)

if(NOT BUNDLE_LIB_SEARCH_DIRS)
  set(BUNDLE_LIB_SEARCH_DIRS "${ENV_LIB_DIR}")
endif(NOT BUNDLE_LIB_SEARCH_DIRS)
message(STATUS "BUNDLE_LIB_SEARCH_DIRS: ${BUNDLE_LIB_SEARCH_DIRS}")


# CMake Modules
SET(CMAKE_MODULE_PATH
  ${PROJECT_BINARY_DIR}/lib/CGAL
  ${PROJECT_BINARY_DIR}/share/cmake/hdf5
  ${PROJECT_BINARY_DIR}/lib/cmake/lapack-3.4.2
  ${CMAKE_SOURCE_DIR}/CMake
  ${CMAKE_MODULE_PATH})

SET(CGAL_DIR
  ${PROJECT_BINARY_DIR}/lib/CGAL)
SET(ENV{HDF5_ROOT_DIR_HINT}
  ${PROJECT_BINARY_DIR})

# option for using Cg
option(USING_CG "option for using cg for imposter render (default: GLSL)" OFF)
if(USING_CG)
  find_package(Cg)
  if(CG_FOUND)
    add_definitions(-DCG)
    message("Cg found!")
    option(USING_ARB_PROFILE "option for using ARB profile for Cg" OFF)
    if(USING_ARB_PROFILE)
      add_definitions(-DCGARB)
    endif(USING_ARB_PROFILE)
  else(CG_FOUND)
    message(SEND_ERROR "Cg NOT found!")
  endif(CG_FOUND)
else(USING_CG)
  message("Using GLSL!")
  add_definitions(-DGLSL)
endif(USING_CG)

# Build output 
set(LIBRARY_OUTPUT_PATH "${CMAKE_BINARY_DIR}/lib")
set(EXECUTABLE_OUTPUT_PATH "${CMAKE_BINARY_DIR}/bin")
mark_as_advanced(LIBRARY_OUTPUT_PATH EXECUTABLE_OUTPUT_PATH)

set(PETSC_ARCH linux-gnu)
set(PETSC_DIR l${PROJECT_SOURCE_DIR}/third-party/petsc)

# Set the revision number from svn.
option(USING_SUBVERSION "If you're using subversion, TexMol can use the revision number for version info" OFF)
set(CVC_SVN_REVISION "0")
if(USING_SUBVERSION)
  find_package(Subversion)
  if(Subversion_FOUND)
    Subversion_WC_INFO(${CMAKE_SOURCE_DIR} TexMol)
    set(CVC_SVN_REVISION ${TexMol_WC_REVISION})
    message(STATUS "Building Revision: ${CVC_SVN_REVISION}")
  endif(Subversion_FOUND)
endif(USING_SUBVERSION)


# The TexMol version number.
SET(TexMol_VERSION_MAJOR 2)
SET(TexMol_VERSION_MINOR 0)
SET(TexMol_VERSION_PATCH ${CVC_SVN_REVISION})

# The full version string
SET(TexMol_VERSION ${TexMol_VERSION_MAJOR}.${TexMol_VERSION_MINOR}.${TexMol_VERSION_PATCH})
message(STATUS "TexMol version: ${TexMol_VERSION}")

# OSX Bundle settings
IF(APPLE)
  SET(CMAKE_BUNDLE_NAME
    "TexMol ${TexMol_VERSION_MAJOR}.${TexMol_VERSION_MINOR}-${TexMol_VERSION_PATCH}")
  SET(CMAKE_BUNDLE_LOCATION "${CMAKE_INSTALL_PREFIX}")
  # make sure CMAKE_INSTALL_PREFIX ends in /
  STRING(LENGTH "${CMAKE_INSTALL_PREFIX}" LEN)
  MATH(EXPR LEN "${LEN} -1" )
  STRING(SUBSTRING "${CMAKE_INSTALL_PREFIX}" ${LEN} 1 ENDCH)
  IF(NOT "${ENDCH}" STREQUAL "/")
    SET(CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}/")
  ENDIF(NOT "${ENDCH}" STREQUAL "/")
  SET(CMAKE_INSTALL_PREFIX 
    "${CMAKE_INSTALL_PREFIX}${CMAKE_BUNDLE_NAME}.app/Contents")
ENDIF(APPLE)




# include macro for setting up Qt
include( SetupQt )
include( SetupFFTW )
include( SetupNFFT )
include( SetupPETSC )
include( SetupBoost )
include( SetupGSL )
include( SetupGLUT )
include( SetupLapack )
include( SetupCGAL )





option(TEXMOL_ENABLE_ROUNDING_MATH "Enable the -frounding-math flag.  Needed for using CGAL with some compiler versions" OFF)
if(TEXMOL_ENABLE_ROUNDING_MATH)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -frounding-math")
endif(TEXMOL_ENABLE_ROUNDING_MATH)

option(TEXMOL_DISABLE_COARSEGRAIN "TexMol needs this on." ON)
OPTION(HAVE_CGAL "Use CGAL dependent functions." ON)
OPTION(HAVE_NFFT "Use NFFT dependent functions." ON)
OPTION(HAVE_PETSC "Use PETSC dependent functions." ON)
OPTION(HAVE_LAPACK "Use Lapack dependent functions." ON)
OPTION(ENABLE_SECONDARY_STRUCTURE "Enable secondary structure elucidation unitility." ON)
OPTION(ENABLE_POCKET_TUNNEL "Enable pocket-tunnel unitility." ON)
option(BUILD_INTERFACESTATS "Enable building of InterfaceStats" ON)
OPTION(BUILD_MOLSURF_API "Enable building molsurf API." ON)

set(ENABLE_SECONDARY_STRUCTURE ON)
set(ENABLE_POCKET_TUNNEL ON)
set(BUILD_INTERFACESTATS ON)
set(BUILD_MOLSURF_API ON)
set(BUILD_GEOMETRY ON)
set(ENABLE_SECONDARY_STRUCTURE ON)
set(ENABLE_POCKET_TUNNEL ON)
set(ENABLE_MULTIRESOL_SURFACE ON)




# **** Print messages for final setup of enabling flags ****
message("*****************************")
message("   Status of build options   ")
message("*****************************")
if(HAVE_LAPACK)
   message("- HAVE_LAPACK flag ENABLED: required for Sec. Struct., Pocket Tunnel, Interfacestats, Geometry and MolSurfAPI")
else(HAVE_LAPACK)
   message("- HAVE_LAPACK flag DISABLED: required for Sec. Struct., Pocket Tunnel, Interfacestats, Geometry and MolSurfAPI")
endif(HAVE_LAPACK)
if(HAVE_CGAL)
   message("- HAVE_CGAL flag ENABLED: required for Sec. Struct. and Pocket Tunnel")
else(HAVE_CGAL)
   message("- HAVE_CGAL flag DISABLED: required for Sec. Struct. and Pocket Tunnel")
endif(HAVE_CGAL)
if(HAVE_NFFT)
   message("- HAVE_NFFT flag ENABLED: required for FastSummation and GB")
else(HAVE_NFFT)
   message("- HAVE_NFFT flag DISABLED: required for FastSummation and GB")
endif(HAVE_NFFT)
if(HAVE_PETSC)
   message("- HAVE_NFFT flag ENABLED: required for KIFMM and PB")
else(HAVE_PETSC)
   message("- HAVE_NFFT flag DISABLED: required for KIFMM and PB")
endif(HAVE_PETSC)
if(HAVE_FFTW)
   message("- HAVE_FFTW flag ENABLED: required for KIFMM, FastSummation, Multiresolution surface and Docking")
else(HAVE_FFTW)
   message("- HAVE_FFTW flag DISABLED: required for KIFMM, FastSummation, Multiresolution surface and Docking")
endif(HAVE_FFTW)
message("*****************************")
if(ENABLE_SECONDARY_STRUCTURE)
   ADD_DEFINITIONS(-DSS)
   message("- Secondary Structure elucidation ENABLED")
else(ENABLE_SECONDARY_STRUCTURE)
   message("- Secondary Structure elucidation DISABLED")
endif(ENABLE_SECONDARY_STRUCTURE)
if(ENABLE_POCKET_TUNNEL)
   ADD_DEFINITIONS(-DPOCKET_TUNNEL)
   message("- Pocket Tunnel ENABLED")
else(ENABLE_POCKET_TUNNEL)
   message("- Pocket Tunnel DISABLED")
endif(ENABLE_POCKET_TUNNEL)
if(BUILD_INTERFACESTATS)
   ADD_DEFINITIONS(-DIFS)
   message("- Build interface stats ENABLED")
else(BUILD_INTERFACESTATS)
   message("- Build interface stats DISABLED")
endif(BUILD_INTERFACESTATS)
if(BUILD_MOLSURF_API)
   ADD_DEFINITIONS(-DMSA)
   message("- Build MolSurfAPI ENABLED")
else(BUILD_MOLSURF_API)
   message("- Build MolSurfAPI DISABLED")
endif(BUILD_MOLSURF_API)
if(ENABLE_MULTIRESOL_SURFACE)
   ADD_DEFINITIONS(-DMS)
   message("- Build Multiresolution surface ENABLED")
else(ENABLE_MULTIRESOL_SURFACE)
   message("- Build Multiresolution surface DISABLED")
endif(ENABLE_MULTIRESOL_SURFACE)
message("*****************************")





# ************* CPack configuration for TexMol *************
# Include the packaging system for distributing binaries
if(WIN32)
  set(CPACK_GENERATOR "NSIS")
elseif(APPLE)
  set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 1)
  set(CPACK_GENERATOR "ZIP")
else(WIN32)
  set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 1)
  set(CPACK_GENERATOR "TGZ")
endif(WIN32)
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Molecular Processing and Visualization")
SET(CPACK_PACKAGE_VENDOR "Computational Visualization Center")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/README")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/README")
SET(CPACK_PACKAGE_VERSION_MAJOR "${TexMol_VERSION_MAJOR}")
SET(CPACK_PACKAGE_VERSION_MINOR "${TexMol_VERSION_MINOR}")
SET(CPACK_PACKAGE_VERSION_PATCH "${TexMol_VERSION_PATCH}")
SET(CPACK_PACKAGE_VERSION "${TexMol_VERSION}")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "TexMol ${TexMol_VERSION_MAJOR}.${TexMol_VERSION_MINOR}")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "TexMol-${TexMol_VERSION}")
SET(CPACK_PACKAGE_NAME "${CMAKE_PROJECT_NAME}")
# Installers for 32- vs. 64-bit CMake:
#  - Root install directory (displayed to end user at installer-run time)
#  - "NSIS package/display name" (text used in the installer GUI)
#  - Registry key used to store info about the installation
IF(CMAKE_CL_64)
  SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
  SET(CPACK_NSIS_PACKAGE_NAME "${CPACK_PACKAGE_INSTALL_DIRECTORY} (Win64)")
  SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION} (Win64)")
ELSE()
  SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
  SET(CPACK_NSIS_PACKAGE_NAME "${CPACK_PACKAGE_INSTALL_DIRECTORY}")
  SET(CPACK_NSIS_DISPLAY_NAME "${CPACK_PACKAGE_INSTALL_DIRECTORY} TexMol")
  SET(CPACK_NSIS_HELP_LINK "http:\\\\\\\\cvcweb.ices.utexas.edu")
  SET(CPACK_NSIS_URL_INFO_ABOUT "http:\\\\\\\\cvcweb.ices.utexas.edu")
  SET(CPACK_NSIS_CONTACT "arand@ices.utexas.edu")
  SET(CPACK_NSIS_MODIFY_PATH ON)
  SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "${CPACK_PACKAGE_NAME} ${CPACK_PACKAGE_VERSION}")
ENDIF()
IF(NOT DEFINED CPACK_SYSTEM_NAME)
  # make sure package is not Cygwin-unknown, for Cygwin just
  # cygwin is good for the system name
  IF("${CMAKE_SYSTEM_NAME}" STREQUAL "CYGWIN")
    SET(CPACK_SYSTEM_NAME Cygwin)
  ELSE("${CMAKE_SYSTEM_NAME}" STREQUAL "CYGWIN")
    SET(CPACK_SYSTEM_NAME ${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR})
  ENDIF("${CMAKE_SYSTEM_NAME}" STREQUAL "CYGWIN")
ENDIF(NOT DEFINED CPACK_SYSTEM_NAME)
IF(${CPACK_SYSTEM_NAME} MATCHES Windows)
  IF(CMAKE_CL_64)
    SET(CPACK_SYSTEM_NAME win64-x64)
  ELSE(CMAKE_CL_64)
    SET(CPACK_SYSTEM_NAME win32-x86)
  ENDIF(CMAKE_CL_64)
ENDIF(${CPACK_SYSTEM_NAME} MATCHES Windows)
IF(NOT DEFINED CPACK_PACKAGE_FILE_NAME)
  # if the CPACK_PACKAGE_FILE_NAME is not defined by the cache
  # default to source package - system, on cygwin system is not 
  # needed
  IF(CYGWIN)
    SET(CPACK_PACKAGE_FILE_NAME "${CPACK_SOURCE_PACKAGE_FILE_NAME}")
  ELSE(CYGWIN)
    SET(CPACK_PACKAGE_FILE_NAME 
      "${CPACK_SOURCE_PACKAGE_FILE_NAME}-${CPACK_SYSTEM_NAME}")
  ENDIF(CYGWIN)
ENDIF(NOT DEFINED CPACK_PACKAGE_FILE_NAME)

SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "Alex Rand") #required
SET(CPACK_PACKAGE_CONTACT "arand@ices.utexas.edu")
SET(CPACK_STRIP_FILES ON)
SET(CPACK_SOURCE_STRIP_FILES "")
SET(CPACK_PACKAGE_EXECUTABLES "TexMol" "TexMol")
SET(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README")
SET(CPACK_RESOURCE_FILE_WELCOME "${CMAKE_SOURCE_DIR}/README")
include( CPack )
include(InstallRequiredSystemLibraries)



option(PRE_BUILD "Builds dependencies" ON)
if(PRE_BUILD)
  ADD_SUBDIRECTORY (third-party)
  MESSAGE(STATUS "*******************************************************")
  MESSAGE(STATUS "** If your expected target is not available, consider")
  MESSAGE(STATUS "** changing the PRE_BUILD option using ccmake.")
  MESSAGE(STATUS "*******************************************************")
else(PRE_BUILD)
  include_directories(${PROJECT_BINARY_DIR}/include)
  link_directories(${PROJECT_BINARY_DIR}/lib)
  ADD_SUBDIRECTORY (src)
  MESSAGE(STATUS "*******************************************************")
  MESSAGE(STATUS "** If needed dependencies are not available, consider")
  MESSAGE(STATUS "** changing the PRE_BUILD option using ccmake.")
  MESSAGE(STATUS "*******************************************************")
endif(PRE_BUILD)

