# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bbauer/Coding/F2Dock/TexMol

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bbauer/Coding/F2Dock/TexMol

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/bbauer/Coding/F2Dock/TexMol/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bbauer/Coding/F2Dock/TexMol/CMakeFiles /home/bbauer/Coding/F2Dock/TexMol//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bbauer/Coding/F2Dock/TexMol/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gmp_proj

# Build rule for target.
gmp_proj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmp_proj
.PHONY : gmp_proj

# fast build rule for target.
gmp_proj/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/gmp_proj.dir/build.make third-party/CMakeFiles/gmp_proj.dir/build
.PHONY : gmp_proj/fast

#=============================================================================
# Target rules for targets named mpfr_proj

# Build rule for target.
mpfr_proj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mpfr_proj
.PHONY : mpfr_proj

# fast build rule for target.
mpfr_proj/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/mpfr_proj.dir/build.make third-party/CMakeFiles/mpfr_proj.dir/build
.PHONY : mpfr_proj/fast

#=============================================================================
# Target rules for targets named boost_proj

# Build rule for target.
boost_proj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 boost_proj
.PHONY : boost_proj

# fast build rule for target.
boost_proj/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/boost_proj.dir/build.make third-party/CMakeFiles/boost_proj.dir/build
.PHONY : boost_proj/fast

#=============================================================================
# Target rules for targets named hdf5_proj

# Build rule for target.
hdf5_proj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hdf5_proj
.PHONY : hdf5_proj

# fast build rule for target.
hdf5_proj/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/hdf5_proj.dir/build.make third-party/CMakeFiles/hdf5_proj.dir/build
.PHONY : hdf5_proj/fast

#=============================================================================
# Target rules for targets named CGAL_proj

# Build rule for target.
CGAL_proj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CGAL_proj
.PHONY : CGAL_proj

# fast build rule for target.
CGAL_proj/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/CGAL_proj.dir/build.make third-party/CMakeFiles/CGAL_proj.dir/build
.PHONY : CGAL_proj/fast

#=============================================================================
# Target rules for targets named lapack_proj

# Build rule for target.
lapack_proj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lapack_proj
.PHONY : lapack_proj

# fast build rule for target.
lapack_proj/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/lapack_proj.dir/build.make third-party/CMakeFiles/lapack_proj.dir/build
.PHONY : lapack_proj/fast

#=============================================================================
# Target rules for targets named fftw_proj

# Build rule for target.
fftw_proj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fftw_proj
.PHONY : fftw_proj

# fast build rule for target.
fftw_proj/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/fftw_proj.dir/build.make third-party/CMakeFiles/fftw_proj.dir/build
.PHONY : fftw_proj/fast

#=============================================================================
# Target rules for targets named nfft_proj

# Build rule for target.
nfft_proj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nfft_proj
.PHONY : nfft_proj

# fast build rule for target.
nfft_proj/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/nfft_proj.dir/build.make third-party/CMakeFiles/nfft_proj.dir/build
.PHONY : nfft_proj/fast

#=============================================================================
# Target rules for targets named petsc_proj

# Build rule for target.
petsc_proj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 petsc_proj
.PHONY : petsc_proj

# fast build rule for target.
petsc_proj/fast:
	$(MAKE) $(MAKESILENT) -f third-party/CMakeFiles/petsc_proj.dir/build.make third-party/CMakeFiles/petsc_proj.dir/build
.PHONY : petsc_proj/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... CGAL_proj"
	@echo "... boost_proj"
	@echo "... fftw_proj"
	@echo "... gmp_proj"
	@echo "... hdf5_proj"
	@echo "... lapack_proj"
	@echo "... mpfr_proj"
	@echo "... nfft_proj"
	@echo "... petsc_proj"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

