const char glslFragmentShader[] =
	"uniform sampler2D lightmap;\n"
	"uniform sampler2D depthmap;\n"
	"uniform sampler2D normalmap;\n"
	"uniform sampler3D AOmap;\n"
	"uniform vec2 AOdelta;\n"
	"uniform vec3 bboxmin;\n"
	"uniform vec3 rAOresol;\n"
	"uniform float ambient;\n"
	"void main() {\n"
	"	vec4 lighting = texture2D(lightmap, gl_TexCoord[0].xy);\n"
	"	vec3 color = gl_Color.xyz*(gl_Color.w + lighting.y) + lighting.z;\n"
	"\n"
	" 	float depthVal = texture2D(depthmap, gl_TexCoord[0].xy).r;\n"
	"\n"
	"	//CHA: depth correction: depth =  Pndc.z / Pndc.w\n"
	"	vec4 epos = gl_TexCoord[1];\n"
	"	epos.z += depthVal*gl_TexCoord[2].w;\n"
	"	vec4 ndcpos = gl_ProjectionMatrix * epos;\n"
	"	gl_FragDepth = (ndcpos.z / ndcpos.w)*0.5+0.5;\n"
	"\n"
	"	//Let's take care of ambient occlusion\n"
	"	vec4 enorm = vec4( texture2D(normalmap, gl_TexCoord[0].xy).rgb, 1.0 );\n"
	"	enorm = enorm * 2.0 - 1.0;\n"
	"	vec4 objnorm = gl_ModelViewMatrixTranspose * enorm;\n"
	"	vec3 AOpos = gl_TexCoord[2].xyz + objnorm.xyz*(gl_TexCoord[2].w + AOdelta.x*0.5);\n"
	"	AOpos = (AOpos - bboxmin) * AOdelta.y;\n"
	"	AOpos = AOpos * rAOresol;\n"
	"	float AOval = texture3D(AOmap, AOpos).r;\n"
	"	if( AOval > 1.0 ) AOval = 1.0;\n"
	"\n"
	"	float opacity = lighting.w;\n"
	"	//gl_FragColor = vec4(color, opacity);\n"
	"	gl_FragColor = vec4(color*(1.0-AOval)+ambient, opacity);\n"
	"}\n";	
