const char glslFragmentFunctionShader[] =
	"uniform sampler2D lightmap;\n"
	"uniform sampler2D depthmap;\n"
	"uniform sampler3D functionmap;\n"
	"uniform vec3 minExtent;\n"
	"uniform vec3 maxExtent;\n"
	"vec3 interpolateColor( vec3 color1, vec3 color2, float left, float right, float val )\n"
	"{\n"
	"	float t = (val - left ) / ( right - left );\n"
	"	return color1*(1.0-t) + color2*t;\n"
	"}\n"
	"void main() {\n"
	" 	float depthVal = texture2D(depthmap, gl_TexCoord[0].xy).r;\n"
	"\n"
	"	//CHA: depth correction: depth =  Pndc.z / Pndc.w\n"
	"	vec4 epos = gl_TexCoord[1];\n"
	"	epos.z += depthVal*gl_TexCoord[2].w;\n"
	"	vec4 ndcpos = gl_ProjectionMatrix * epos;\n"
	"	gl_FragDepth = (ndcpos.z / ndcpos.w)*0.5+0.5;\n"
	"\n"
	"	vec4 objpos = gl_ModelViewMatrixInverse * epos;\n"
	"	vec3 unit = (objpos.xyz - minExtent.xyz) / ( maxExtent.xyz - minExtent.xyz);\n"
	"	float dens = texture3D( functionmap, unit ).r;\n"
	"	vec3 surfaceColor = vec3(0.0, 0.0, 0.0);\n"
	"	if( dens >= 0.0 && dens < 0.46 )\n"
	"	{\n"
	"		surfaceColor = interpolateColor( vec3(0.5,0.0,0.0), vec3(1.0,0.0,0.0), 0.0, 0.46, dens );\n"
	"	}\n"
	"	else if( dens >= 0.46 && dens < 0.5 )\n"
	"	{\n"
	"		surfaceColor = interpolateColor( vec3(1.0,0.0,0.0), vec3(0.0,0.0,0.0), 0.46, 0.5, dens );\n"
	"	}\n"
	"	else if( dens >= 0.5 && dens < 0.529 )\n"
	"	{\n"
	"		surfaceColor = interpolateColor( vec3(0.0,0.0,0.0), vec3(0.0,1.0,0.0), 0.5, 0.529, dens );\n"
	"	}\n"
	"	if( dens >= 0.529 && dens <= 1.0 )\n"
	"	{\n"
	"		surfaceColor = interpolateColor( vec3(0.0,1.0,0.0), vec3(0.0,0.5,0.0), 0.529, 1.0, dens );\n"
	"	}	\n"
	"	\n"
	"	vec4 lighting = texture2D(lightmap, gl_TexCoord[0].xy);\n"
	"	vec3 color = surfaceColor.xyz*(gl_Color.w + lighting.y) + lighting.z;\n"
	"	float opacity = lighting.w;\n"
	"	gl_FragColor = vec4(color, opacity);\n"
	"}\n";	
