const char glslHelixVertexShader[] =
	"void main() {\n"
	"	//set texture coordniate\n"
	"	gl_TexCoord[3] = vec4(gl_Vertex.x, (gl_Vertex.y+1.0)*0.5, 0.0, 0.0 );\n"
	"\n"
	"	// eye_space_offset = radius * v[OPOS]\n"
	"	float radius = gl_Vertex.z;\n"
	"\n"
	"	// get vector from P1 to P2\n"
	"	vec4 axis = gl_MultiTexCoord1 - gl_MultiTexCoord0;\n"
	"\n"
	"	vec4 eye_space_axis = normalize( gl_ModelViewMatrix * axis );\n"
	"	float h = 1.0 / sqrt(1.0-eye_space_axis.z*eye_space_axis.z);\n"
	"\n"
	"	//float4 eye_space_offset = radius * float4(IN.offset.xyz, 0.0);\n"
	"	vec4 unit_eye_space_offset = normalize(vec4(eye_space_axis.y,-eye_space_axis.x , 0, 0));\n"
	"	vec4 eye_space_offset = unit_eye_space_offset * gl_Vertex.y * radius;\n"
	"\n"
	"	eye_space_offset = eye_space_offset + eye_space_axis * -h*radius * eye_space_axis.z;\n"
	"\n"
	"	// object_space_offset = INV_MV * eye_space_offset\n"
	"	vec4 object_space_offset = gl_ModelViewMatrixInverse * eye_space_offset;\n"
	"\n"
	"	// offsetRadius.x = 0 or 1 for points near p0 or p1. \n"
	"	// obtain the output position in object space\n"
	"	// assume that w is correct\n"
	"	vec4 p = gl_MultiTexCoord0 + axis*gl_Vertex.x + object_space_offset;\n"
	"\n"
	"	//CHA: send eye position to fragment shader for depth correction\n"
	"	gl_TexCoord[2] = gl_ModelViewMatrix * p;\n"
	"	//CHA: send radius to fragment shader for depth correction\n"
	"	gl_TexCoord[2].w = radius;\n"
	"\n"
	"	// clip coordinates\n"
	"	// IN.p2 has the position\n"
	"	gl_Position = gl_ModelViewProjectionMatrix * p;\n"
	"\n"
	"	gl_FrontColor = gl_Color;\n"
	"\n"
	"	// calculate normal-space light vector\n"
	"	// float4 lightVect = float4(00,100,140,1) - p;\n"
	"	vec4 lightVect = vec4(50,100,140,0);\n"
	"	lightVect = normalize(lightVect);\n"
	"\n"
	"	gl_TexCoord[0] = vec4(gl_Vertex.y*0.5+0.5,0,0,1);\n"
	"	gl_TexCoord[1] = gl_TexCoord[0];\n"
	"	gl_TexCoord[1].y = 0.5;\n"
	"\n"
	"	// xform light vector into eye space\n"
	"\n"
	"	vec4 eyeLightVec = lightVect; //mul(ModelViewIT, lightVect);\n"
	"	eyeLightVec = vec4(dot(unit_eye_space_offset, eyeLightVec), \n"
	"			 dot(eye_space_axis, eyeLightVec),\n"
	"			 dot(cross(unit_eye_space_offset.xyz, eye_space_axis.xyz), eyeLightVec.xyz),//eyeLightVec.z,\n"
	"			 0);\n"
	"\n"
	"	// Range compress light vector to fit in a color\n"
	"	gl_FrontSecondaryColor.xyz = eyeLightVec.xyz * 0.5 + 0.5;\n"
	"\n"
	"}\n";
