const char glslHelixFragmentShader[] =
	"uniform vec4 maincolor;\n"
	"uniform sampler1D normalmap;\n"
	"uniform sampler2D depthmap;\n"
	"uniform sampler2D opacitymap;\n"
	"uniform sampler2D silhouettemap;\n"
	"uniform vec3 silhouettecolor;\n"
	"uniform float specweight;\n"
	"vec3 expand(vec3 vector)\n"
	"{\n"
	"    return 2.0 * (vector - 0.5);\n"
	"}\n"
	"float saturate(float x)\n"
	"{\n"
	"	return max(min(x, 1.0), 0.0);\n"
	"}\n"
	"\n"
	"vec3 normalize1(vec3 vector)\n"
	"{\n"
	"    float VdotV = dot(expand(vector), expand(vector));\n"
	"    return (vector-0.5)*(1.0-saturate(VdotV)) + expand(vector);\n"
	"}\n"
	"vec3 normalize2(vec3 vector)\n"
	"{\n"
	"    float VdotV = dot(vector, vector);\n"
	"    return vector * inversesqrt( VdotV );\n"
	"}\n"
	"void main() {\n"
	"	vec4 normal = 2.0 * (texture1D(normalmap, gl_TexCoord[0].x) - 0.5);\n"
	"	vec3 lvec = normalize1(gl_SecondaryColor.xyz);\n"
	"\n"
	"	float NdotL = dot(normal.xyz, lvec);\n"
	"	vec3 color = gl_Color.xyz*(saturate(NdotL) + gl_Color.w);\n"
	"\n"
	"	// calculate reflection vector\n"
	"	// R = 2 * (N * (N dot L) - L/2)\n"
	"	//   = 2 * N * (N dot L) - L\n"
	"	//float3 reflectVec = ((NdotL * normal.rgb) + (-0.5 * IN.secondarycolor)) * 2.0;\n"
	"	vec3 reflectVec = normal.xyz * NdotL * 2.0 - lvec;\n"
	"	reflectVec = normalize2( reflectVec );\n"
	"\n"
	"	// eye vector E = (0, 0, 1)\n"
	"	// R dot E = (R.r*0.0 + R.g*0.0 + R.b*1.0) = R.b\n"
	"	float RdotE = saturate(reflectVec.b);\n"
	"\n"
	"	// calculate specular as pow(RdotE, 16)\n"
	"	float specular = pow(RdotE, 16.0); \n"
	"\n"
	"	// add specular light contribution to final color\n"
	"	color += specular * specweight;\n"
	"\n"
	"	float depthVal = texture2D(depthmap, gl_TexCoord[1].xy).r;\n"
	"\n"
	"	//CHA: depth correction: depth = p_ndc.z / p_ndc.w\n"
	"	vec4 epos = vec4(gl_TexCoord[2].xyz, 1.0);\n"
	"	epos.z += depthVal * gl_TexCoord[2].w;\n"
	"	vec4 ndcpos = gl_ProjectionMatrix * epos;\n"
	"	gl_FragDepth = (ndcpos.z / ndcpos.w)*0.5+0.5;\n"
	"\n"
	"	float opacity = texture2D(opacitymap, gl_TexCoord[3].xy).r;\n"
	"	float silhouette = texture2D(silhouettemap, gl_TexCoord[3].xy).r;\n"
	"	gl_FragColor = vec4(color*opacity*(1.0-silhouette) + silhouettecolor*silhouette, silhouette + opacity);\n"
	"}\n";
