const char glslVertexShader[] =
	"void main() {\n"
	"	vec4 offset = vec4(0.0, 0.0, 0.0, 0.0);\n"
	"	float ambient = 0.0;\n"
	"	if(gl_Vertex.w == 0.0) {\n"
	"		offset  = vec4( -1.0, -1.0, -1.0, 1.0 );\n"
	"		ambient = 0.1;\n"
	"	}\n"
	"	else if(gl_Vertex.w == 1.0) {\n"
	"		offset  = vec4( 1.0, -1.0, -1.0, 1.0 );\n"
	"		ambient = 0.6;\n"
	"	}\n"
	"	else if(gl_Vertex.w == 2.0) {\n"
	"		offset  = vec4( 1.0, 1.0, -1.0, 1.0 );\n"
	"		ambient = 0.1;\n"
	"	}\n"
	"	else if(gl_Vertex.w == 3.0) {\n"
	"		offset  = vec4( -1.0, 1.0, -1.0, 1.0 );\n"
	"		ambient = 0.1;\n"
	"	}\n"
	"	float radius = gl_Color.w;\n"
	"	//set texture coordinate for depth correction\n"
	"	gl_TexCoord[0] = (offset + 1.0)*0.5;\n"
	"	//CHA: send center of sphere for ambient occlusion computation\n"
	"	gl_TexCoord[2].xyz = gl_Vertex.xyz;\n"
	"	//CHA: send radius to fragment shader for depth correction\n"
	"	gl_TexCoord[2].w = radius;\n"
	"	vec4 position = gl_Vertex;\n"
	"	position.w = 1.0;\n"
	"	\n"
	"	// eye_space_offset = radius * v[OPOS]\n"
	"	vec4 eye_space_offset = radius * vec4(offset.x, offset.y, 0.0, 0.0);\n"
	"	\n"
	"	// object_space_offset = INV_MV * eye_space_offset\n"
	"	vec4 object_space_offset =  gl_ModelViewMatrixInverse * eye_space_offset;\n"
	"	\n"
	"	position.xyz = position.xyz + object_space_offset.xyz;\n"
	"	// CHA: send eye postion to fragment shader for depth correction\n"
	"	gl_TexCoord[1] = gl_ModelViewMatrix * position;\n"
	"	// clip coordinates\n"
	"	gl_Position =  gl_ModelViewProjectionMatrix * position;\n"
	"	\n"
	"	gl_FrontColor.xyz = gl_Color.xyz;\n"
	"	gl_FrontColor.w = ambient;\n"
	"	\n"
	"}\n";
