# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += Geometry


# Input
INCLUDEPATH += ../UsefulMath
INCLUDEPATH += ../Include


SOURCES =  \
		Geometry.cpp \
		GeometryScene.cpp \
		GeometrySceneArray.cpp \
		IntQueue.cpp \
		MeshDerivatives.cpp \
		MyExtensions.cpp \ 
		SceneArrayNode.cpp \
		Texture2D.cpp

HEADERS =  \
		Geometry.h \
		GeometryScene.h \
		GeometrySceneArray.h \
		IntQueue.h \
		MeshDerivatives.h \ 
		MyExtensions.h \ 
		SceneArrayNode.h \
		Texture2D.h

