# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += Summation

INCLUDEPATH += ../UsefulMath

# Input

SOURCES =  \
		DirectToGridSummationModule.cpp \
		DirectToScatteredPointsSummationModule.cpp \
		FourierBasedToGridSummationModule.cpp \
		FourierBasedToScatteredPointsSummationModule.cpp \
		GaussianKernel.cpp \
		Kernel.cpp \
		NonUniformOutputGrid.cpp \
		OutputGrid.cpp \
		SummationModule.cpp \
		UniformOutputGrid.cpp

HEADERS =  \
		DirectToGridSummationModule.h \
		DirectToScatteredPointsSummationModule.h \
		FourierBasedToGridSummationModule.h \
		FourierBasedToScatteredPointsSummationModule.h \
		GaussianKernel.h \
		Kernel.h \
		NonUniformOutputGrid.h \
		OutputGrid.h \
		SummationModule.h \
		UniformOutputGrid.h

