# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += Curvatures


# Input

INCLUDEPATH += ../UsefulMath

SOURCES =  \
		Curvature.cpp \
		CurvaturesGridVoxel.cpp \
		SumOfGaussiansCurvature.cpp

HEADERS =  \
		Curvature.h \
		CurvaturesGridVoxel.h \
		SumOfGaussiansCurvature.h

