# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib opengl create_prl
TARGET  += Contouring

# Input
INCLUDEPATH += ../Geometry
INCLUDEPATH += ../UsefulMath

SOURCES =  \
		Contour.cpp \
		ContourExtractor.cpp \
		ContourGeometry.cpp \
		MarchingCubesBuffers.cpp \
		MultiContour.cpp \
		RGBAExtractor.cpp \
		SingleExtractor.cpp

HEADERS =  \
		Contour.h \
		ContourExtractor.h \
		ContourGeometry.h \
		cubes.h \
		MarchingCubesBuffers.h \
		MultiContour.h \
		RGBAExtractor.h \
		SingleExtractor.h

