# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += AdaptiveIsocontouring


# Input

SOURCES =  \
		bishoulder.cpp \
		cell.cpp \
		cellQueue.cpp \
		contouring.cpp \
		geoframe.cpp \
		utility.cpp 

HEADERS =  \
		cell.h \
		cellQueue.h \
		comp.h \
		contouring.h \
		geoframe.h 

