# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += ARM


# Input

INCLUDEPATH += ../../
INCLUDEPATH += ../../Blurmaps
INCLUDEPATH += ../../ByteOrder
INCLUDEPATH += ../../Curvatures
INCLUDEPATH += ../../Geometry
INCLUDEPATH += ../../GeometryFileTypes
INCLUDEPATH += ../../GOAFileTypes
INCLUDEPATH += ../../PDBParser
INCLUDEPATH += ../../UsefulMath
INCLUDEPATH += ../../VolumeFileTypes
INCLUDEPATH += ../../SphericalPatchIntersections
INCLUDEPATH += ../OptimizerLib/Optimizer

SOURCES =  \
		ARM.cpp
HEADERS =  \
		ARM.h

