# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += C2C
DEFINES += LINUX _LITTLE_ENDIAN ARITH_ENCODE ARITH_DECODE UNIQUE ZP_CODEC 

# Input
INCLUDEPATH += ./arithlib
INCLUDEPATH += ./arithlib/libdjvu++

SOURCES =  \
		bufferedio.cpp \
		c2c_codec.cpp \
		ContourGeom.cpp \
		layer.cpp \
		rawslicefac.cpp \
		rawvslicefac.cpp \
		slice.cpp \
		slicecache.cpp \
		util.cpp \
		vertex.cpp \
		arithlib/arithdecode.cpp \
		arithlib/bitbuffer.cpp \
		arithlib/coder.cpp \
		arithlib/encode.cpp \
		arithlib/stats.cpp \
		arithlib/utils.cpp \
        arithlib/libdjvu++/ByteStream.cpp \
        arithlib/libdjvu++/GContainer.cpp \
        arithlib/libdjvu++/GException.cpp \
        arithlib/libdjvu++/GSmartPointer.cpp \
        arithlib/libdjvu++/ZPCodec.cpp

HEADERS =  \
		blockfac.h \
		bufferedio.h \
		c2c_codec.h \
		c2cbuf.h \
		config.h \
		contour.h \
		ContourGeom.h \
		cubes.h \
		decode.h \
		diskio.h \
		filec2cbuf.h \
		layer.h \
		rawreader.h \
		rawslicefac.h \
		rawvreader.h \
		rawvslicefac.h \
		singlecs.h \
		slice.h \
		slicecache.h \
		slicefac.h \
		streamc2cbuf.h \
		trimesh.h \
		util.h \
		vertex.h \
		vtkMarchingCubesCases.h \
		arithlib/arith.h \
		arithlib/arith_defines.h \
		arithlib/bitbuffer.h \
		arithlib/coder.h \
		arithlib/encode.h \
		arithlib/stats.h \
		arithlib/unitypes.h \
		arithlib/utils.h \
        arithlib/libdjvu++/ByteStream.h \
        arithlib/libdjvu++/GContainer.h \
        arithlib/libdjvu++/GException.h \
        arithlib/libdjvu++/GSmartPointer.h \
        arithlib/libdjvu++/ZPCodec.h
