cmake_minimum_required(VERSION 3.5)

SET(NAME "PB2")

FILE(GLOB SOURCE_FILES *.cpp)
FILE(GLOB INCLUDE_FILES ${CMAKE_SOURCE_DIR}/../../inc/${NAME}/*.[Hh])

SOURCE_GROUP("Source Files" FILES ${SOURCE_FILES})
SOURCE_GROUP("Header Files" FILES ${HEADER_FILES})

INCLUDE_DIRECTORIES(/usr/include)
INCLUDE_DIRECTORIES(../../inc)
INCLUDE_DIRECTORIES(../../inc/KIFMM3D/fmm3d)
INCLUDE_DIRECTORIES(../../inc/KIFMM3D)
INCLUDE_DIRECTORIES($ENV{PETSC_DIR}/$ENV{PETSC_ARCH}/include)
INCLUDE_DIRECTORIES($ENV{PETSC_DIR}/include)
INCLUDE_DIRECTORIES(${PETSC_INCLUDES})

ADD_LIBRARY(${NAME} STATIC ${SOURCE_FILES} ${INCLUDE_FILES})

SetupBoost(${NAME})
SetupPETSC(${NAME})
