// this is the fragment program

/*struct inputs
{
	float4 color : COLOR0;
	float4 color1 : COLOR1;
	//float4 texcoord : TEXCOORD0;
	//float4 texcoord1 : TEXCOORD1;
};*/

struct inputs
{
	float4 HPOS : POSITION;
	float4 texcoord : TEXCOORD0;
	float4 texcoord1 : TEXCOORD1;
	float4 texcoord2 : TEXCOORD2;
	float4 texcoord3 : TEXCOORD3;	// duplicate of HPOS to read it
	float4 primarycolor : COLOR0;
	float3 secondarycolor : COLOR1;
};

float3 expand(float3 vector)
{
    return 2.0 * (vector - 0.5);
}

// register combiner vector normalization function
float3 normalize(float3 vector)
{
    float3 VdotV = dot(expand(vector), expand(vector));
    return (1-saturate(VdotV)) * (vector-0.5) + expand(vector);
}

float3 interpolateColor( float3 color1, float3 color2, float left, float right, float val )
{
	float t = (val - left ) / ( right - left );
	return (1-t)*color1 + t*color2;
}

float4 main(inputs IN, out float depth: DEPTH,
			uniform float4 maincolor,
			uniform sampler2D normalmap,
			uniform sampler2D depthmap,
			uniform sampler3D functionmap,
			uniform float4x4 ModelViewProjInverse,
			uniform float3 minExtent,
			uniform float3 maxExtent
			) : COLOR
{
	// calculate depth
    float3 depthVal = tex2D(depthmap, IN.texcoord.xy).rgb;
    float z = dot(IN.texcoord1.xyz, depthVal);
    float w = dot(IN.texcoord2.xyz, depthVal);
    depth = (z / w);//*0.5+0.5;    

	float mydepth = depth-0.5;
	mydepth = mydepth*2.0;
	// get object pos to look up into texture
	float4 ndcPos = float4( IN.texcoord3.x, IN.texcoord3.y, mydepth, 1.0 );
	//float4 ndcPos = IN.texcoord3;
	float4 objectPos = mul(ModelViewProjInverse,ndcPos);

	// compress object pos into unit cube
	float unitx = (objectPos.x - minExtent[0]) / (maxExtent[0] - minExtent[0]);
	float unity = (objectPos.y - minExtent[1]) / (maxExtent[1] - minExtent[1]);
	float unitz = (objectPos.z - minExtent[2]) / (maxExtent[2] - minExtent[2]);
	
	// do a color map lookup, but now just do something ....
	float4 dens = tex3D( functionmap, float3(unitx, unity, unitz));

	float3 surfaceColor;

	if( dens.r >= 0 && dens.r < 0.46 )
	{
		surfaceColor = interpolateColor( float3(0.5,0,0), float3(1,0,0), 0, 0.46, dens.r );
	}
	if( dens.r >= 0.46 && dens.r < 0.5 )
	{
		surfaceColor = interpolateColor( float3(1,0,0), float3(0,0,0), 0.46, 0.5, dens.r );
	}
	if( dens.r >= 0.5 && dens.r < 0.529 )
	{
		surfaceColor = interpolateColor( float3(0,0,0), float3(0,1,0), 0.5, 0.529, dens.r );
	}
	if( dens.r >= 0.529 && dens.r <= 1.0 )
	{
		surfaceColor = interpolateColor( float3(0,1,0), float3(0,0.5,0), 0.529, 1.0, dens.r );
	}	
	
	//float3 normal = (tex2D(normalmap, IN.texcoord1.xy)).rgb;
	float4 normal = 2.0 * (tex2D(normalmap, IN.texcoord.xy) - 0.5);
	
	//IN.secondarycolor.rgb = 2.0*(IN.secondarycolor.rgb-0.5);
	IN.secondarycolor.rgb = normalize(IN.secondarycolor.rgb);

	float3 NdotL = dot(normal.rgb, IN.secondarycolor);
	// instead of using input color, use the newly computed surface color
	//float3 color = IN.primarycolor.rgb*(saturate(NdotL) + IN.primarycolor.w);
	float3 color = surfaceColor.rgb*(saturate(NdotL) + IN.primarycolor.w);

    // calculate reflection vector
    // R = 2 * (N * (N dot L) - L/2)
    //   = 2 * N * (N dot L) - L
    float3 reflectVec = ((NdotL * normal.rgb) + (-0.5 * IN.secondarycolor)) * 2.0;

    // eye vector E = (0, 0, 1)
    // R dot E = (R.r*0 + R.g*0 + 1*R.b) = R.b
    float RdotE = saturate(reflectVec.b);   // max(0, RdotE);

    // calculate specular as pow(RdotE, 16)
	float specular = pow(RdotE, 16); 

	// add specular light contribution to final color
    //finalColor += specular;
	color += specular;

	float4 outcolor = float4(color, normal.w);    
	return outcolor;
}