# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += Blurmaps


# Input

INCLUDEPATH += ../
INCLUDEPATH += ../ByteOrder
INCLUDEPATH += ../Curvatures
INCLUDEPATH += ../Geometry
INCLUDEPATH += ../GeometryFileTypes
INCLUDEPATH += ../GOAFileTypes
INCLUDEPATH += ../PDBParser
INCLUDEPATH += ../UsefulMath
INCLUDEPATH += ../VolumeFileTypes
INCLUDEPATH += ../SphericalPatchIntersections

SOURCES =  \
		AreaVolume.cpp \
		AtomPopulator.cpp \
		BlurMapsDataManager.cpp \
		CurvaturesGrid.cpp \
		CurvaturesGridVoxel.cpp \
		GOABlur.cpp \
		InOutOctree.cpp \
		MergeVolumes.cpp \
		MolecularSurface.cpp \
		MultilevelBlur.cpp \
		RadiusOptimizer.cpp \
		SignDistanceMolSurface.cpp \
		SimpleVolumeData.cpp \
		SkinRegion.cpp \
		SkinRegion2.cpp \
		SurfaceAtomExtractor.cpp

HEADERS =  \
		AreaVolume.h \
		AtomPopulator.h \
		BlurMapsDataManager.h \
		CurvaturesGrid.h \
		CurvaturesGridVoxel.h \
		GOABlur.h \
		InOutOctree.h \
		MergeVolumes.h \
		MolecularSurface.h \
		MultilevelBlur.h \
		RadiusOptimizer.h \
		SignDistanceMolSurface.h \
		SimpleVolumeData.h \
		SkinRegion.h \
		SkinRegion2.h \
		SurfaceAtomExtractor.h


