# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += SphericalPatchIntersections


# Input

SOURCES =  \
		SphericalPatch.cpp

HEADERS =  \
		SphericalPatch.h 


