# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib opengl create_prl
TARGET  += HLevelSet


QMAKE_CXXFLAGS += $$(CPPFLAGS)
QMAKE_LFLAGS += $$(LDFLAGS)

INCLUDEPATH += ../Blurmaps
INCLUDEPATH += ../PDBParser
INCLUDEPATH += ../UsefulMath
INCLUDEPATH += ../LBIE_lib
INCLUDEPATH += ../Geometry
INCLUDEPATH += ../



# Input

SOURCES = \
		HLevelSet_SES.cpp 

HEADERS = \ 
		HLevelSet.h \
                Misc.h 
