# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += PDBParser

INCLUDEPATH += ../UsefulMath
#INCLUDEPATH += ../ColorManager

# Input

SOURCES =  \
		Atom.cpp \
		BiomoleculeTransformations.cpp \
		ChainData.cpp \
		CollectionData.cpp \
#		GOAColor.cpp \
		GOAFileIO.cpp \
		GOAMolGeometry.cpp \
		GOAVector.cpp \
		GroupOfAtoms.cpp \
		IntQueue.cpp \
		MoleculeMorph.cpp \
		MutatedAtomInformation.cpp \
		parserPDBtoGOA.cpp \
		PDBHeaderParser.cpp \
		ProteinData.cpp \
		ResidueData.cpp \
		ResidueHeader.cpp \
		Residues.cpp \
		SecondaryStructureData.cpp

HEADERS =  \
		Atom.h \
		BiomoleculeTransformations.h \
		ChainData.h \
		CollectionData.h \
		ElementInformation.h \
		ExpandableArray.h \
#		GOAColor.h \
		GOAFileIO.h \
		GOAMolGeometry.h \
		GOAVector.h \
		GroupOfAtoms.h \
		IntQueue.h \
		MoleculeMorph.h \
		MutatedAtomInformation.h \
		parserPDBtoGOA.h \
		ProteinData.h \
		ResidueData.h \
		ResidueHeader.h \
		ResidueInformation.h \
		Residues.h \
		SecondaryStructureData.h

