cmake_minimum_required(VERSION 3.5)

FILE(GLOB SOURCE_FILES 
  ./*.cpp
  ./*.cc
)

FILE(GLOB QT_UI_FORMS 
  ./*.ui
)


FILE(GLOB INCLUDE_FILES 
  ../../inc/DPG/*.[Hh]
)


SOURCE_GROUP("Source Files" FILES ${SOURCE_FILES})
SOURCE_GROUP("Header Files" FILES ${HEADER_FILES})

INCLUDE_DIRECTORIES(
  ../../inc
  ${CMAKE_BINARY_DIR}/src/DPG
  ../../inc/DPG
)

ADD_LIBRARY(DPG STATIC 
	${SOURCE_FILES}
	${INCLUDE_FILES}
)

SET(DAG_LINK_LIBS DPG)

ADD_EXECUTABLE (TestPG DPG.cpp)
TARGET_LINK_LIBRARIES(TestPG ${DAG_LINK_LIBS})

