cmake_minimum_required(VERSION 3.5)

FILE(GLOB SOURCE_FILES *.cpp)
FILE(GLOB INCLUDE_FILES ../../../inc/KIFMM3D/common/*.[Hh])

SOURCE_GROUP("Source Files" FILES ${SOURCE_FILES})
SOURCE_GROUP("Header Files" FILES ${HEADER_FILES})

INCLUDE_DIRECTORIES(
  ../../../inc
  ../../../inc/KIFMM3D/common
)

ADD_LIBRARY (KIFMM3DCommon STATIC ${SOURCE_FILES} ${INCLUDE_FILES})
