# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += PocketTunnel

INCLUDEPATH += ../Geometry
INCLUDEPATH += ../


#linux-g++ {
#        INCLUDEPATH += $(CGALINCLUDE)
#        INCLUDEPATH += $(CGALCONFIG)
#}
#linux-g++-64 {
#        INCLUDEPATH += $(CGALINCLUDE)
#        INCLUDEPATH += $(CGALCONFIG)
#}
# Input

QMAKE_CXXFLAGS += $$(CPPFLAGS)
QMAKE_LDFLAGS += $$(LDFLAGS)


SOURCES =  \
		pocket_tunnel.C \
		handle.C \
		hfn_util.C \
		init.C \
		intersect.C \
		op.C \
		rcocone.C \
		robust_cc.C \
		smax.C \
		tcocone.C \
		curation.C \
		util.C

HEADERS =  \
		datastruct_pt.h \
		tcocone.h \
		rcocone.h \
		util.h \
		init.h \
		smax.h \
		pocket_tunnel.h \
		curation.h \
		handle.h

