# qmake project generated by QMsDev
#
# General settings

TEMPLATE = lib
CONFIG  += qt warn_off staticlib create_prl
TARGET  += Pocket

INCLUDEPATH += ../PDBParser
INCLUDEPATH += ../Blurmaps
INCLUDEPATH += ../GeometryFileTypes
INCLUDEPATH += ../UsefulMath
INCLUDEPATH += ../Geometry
INCLUDEPATH += ../
INCLUDEPATH += ../VolumeFileTypes
INCLUDEPATH += ../SignDistanceFunction_v2

# Input

SOURCES =  \
	Pocket.cpp 

HEADERS =  \
		Pocket.h 

