
  MARK_AS_ADVANCED(LAPACK_LIB)
  MARK_AS_ADVANCED(BLAS_LIB)

  SET(LAPACK_LIB_SEARCHPATH
    ${PROJECT_BINARY_DIR}/lib
    /usr/lib/lapack
    /usr/local/lib/lapack
    C:/MinGW/msys/1.0/local
    $ENV{TACC_LAPACK_LIB}
  )

  FIND_LIBRARY(LAPACK_LIB liblapack.a ${LAPACK_LIB_SEARCHPATH})
  FIND_LIBRARY(BLAS_LIB libblas.a ${LAPACK_LIB_SEARCHPATH})

  #MESSAGE(LAPACK_INCLUDE: ${LAPACK_INCLUDE})
