
  SET(MPFRCPP_INC_SEARCHPATH
    /sw/include
    /usr/include
    /usr/local/include
    /usr/include/mpfrc++
    /usr/local/include/mpfrc++
    $ENV{_NMI_PREREQ_mpfr_ROOT}/include
    C:/MinGW/msys/1.0/local
    $ENV{TACC_MPFRCPP_INC}
  )

  FIND_PATH(MPFRCPP_INCLUDE_PATH mpreal.h ${MPFRCPP_INC_SEARCHPATH})

  IF(MPFRCPP_INCLUDE_PATH)
    SET(MPFRCPP_INCLUDE ${MPFRCPP_INCLUDE_PATH})
  ENDIF (MPFRCPP_INCLUDE_PATH)

  IF(MPFRCPP_INCLUDE)
    INCLUDE_DIRECTORIES( ${MPFRCPP_INCLUDE})
  ENDIF(MPFRCPP_INCLUDE)

  GET_FILENAME_COMPONENT(MPFRCPP_INSTALL_BASE_PATH ${MPFRCPP_INCLUDE_PATH} PATH)

  SET(MPFRCPP_LIB_SEARCHPATH
    ${MPFRCPP_INSTALL_BASE_PATH}
    /usr/lib/mpfrc++
    /usr/local/lib/mpfrc++
    C:/MinGW/msys/1.0/local
    $ENV{TACC_MPFRCPP_LIB}
  )

  FIND_LIBRARY(MPFRCPP_LIB mpreal ${MPFRCPP_LIB_SEARCHPATH})

  IF(MPFRCPP_LIB)
    SET(MPFRCPP_FOUND 1)
  ENDIF(MPFRCPP_LIB)

  MESSAGE(MPFRCPP_INCLUDE: ${MPFRCPP_INCLUDE})
