#ifndef _PB2Enum_H_
#define _PB2Enum_H_


enum GEOMETRY_TYPE {GEOMETRY_LINEAR, GEOMETRY_ASPLINE};
enum LINEAR_SOLVER_TYPE {LIN_SOLVE_GMRES, LIN_SOLVE_LU};
enum BIE_FORMULATION {FORMULATION_NBIE, FORMULATION_DBIE, FORMULATION_DBIE2,FORMULATION_ZERO_ION};
enum DISCRETIZATION_METHOD {DISCRETE_NYSTROM, DISCRETE_COLLOCATION, DISCRETE_COLLOCATION_CONSTANT};

#endif
